### ISSUE TITLE
API Key invalid

### ISSUE THREAD

**Issue by ghost** [grenagit/MMM-APOD#1]
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
MMM-APOD.js:165
```

also when i put my own api key in, it starts playing a video, idk

**Comment by grenagit** [comment]
If I understood the issue correctly, the APOD is not displayed due to a problem accessing the resource (403 HTTP error) ?

1. Is the data accessible (xxxx to be replaced with your personal API key)?
`https://api.nasa.gov/planetary/apod?api_key=xxxx`

2. What happens with the following test configuration?
```js
config: {
	appid: "DEMO_KEY",
}
```

3. Does the problem persist after a restart of MagicMirror?
